server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone:  http://eurekaserver:eurekaserver@localhost:8081/eureka/
spring:
  application:    name: gateway-service
  cloud:    gateway:      routes:      - id: location-service
        uri: http://localhost:8083/
        predicates:        - Path=/location/**
        filters:
        - AddRequestHeader=first-request, first-request-header
        - AddResponseHeader=first-response, first-response-header
      - id: weather-info
        uri: http://localhost:8082/
        predicates:        - Path=/weatherInfo/** 
        filters:
         - AddRequestHeader=second-request, second-request-header
         - AddResponseHeader=second-response, second-response-header