spring:
  application:
    name: location-service
server:
  port: 8083
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:eurekaserver@localhost:8081/eureka/
  instance:
    hostname: localhost